const SONGS = {
  'The Edge': {
    10.2: 'I feel you on the edge',
    12.7: 'The edge of my life',
    16.4: 'Drivin\' a perfect wedge',
    18.7: 'Straight into my mind',
    20.2: 'Come out from under',
    22.8: 'All these indecisions',
    25.9: 'Oh, make room for somebody else',
    31.2: 'Circlin\' the edge',
    34.7: 'Way up high',
    37.4: 'Don\'t know if I\'ll ever have a useful alibi',
    43.6: 'Gone too far to stop',
    47.1: 'Yeah, I\'ve tried',
    49.7: 'Flying, crashing, fuckin\' for a perfect suicide',
    55.7: 'Circlin\' the-',
    80.6: 'Circlin\' the edge',
    86.7: 'Circlin\' the edge',
    95.2: 'Drinkin\' and smokin\' yourself',
    98.3: 'Don\'t even wanna try',
    101.3: 'Make room for somebody else',
    104.4: 'Oh, I just wanna hide',
    106.7: 'Out from under',
    109.1: 'All these indecisions',
    112.1: 'Oh',
    113.6: 'Make room for somebody else',
    117.5: 'Circlin\' the edge',
    121.1: 'Way up high',
    123.7: 'Don\'t know if I\'ll ever have a useful alibi',
    129.7: 'Gone too far to stop',
    133.3: 'Yeah, I\'ve tried',
    136.1: 'Flying, crashing, fuckin\' for a perfect suicide',
    142.1: 'Circlin\' the edge-',
    166.7: 'Circlin\' the edge',
    172.9: 'Circlin\' the edge',
    179.1: '(Circlin\' the edge)',
    185.2: '(Circlin\' the edge)',
  },
  'Homicide': {
    4.1: 'Son, you know why you the greatest alive?',
    7.7: 'Why, Dad?',
    8.9: 'Because you came out of my balls, nigga',
    12.1: 'Hahahahahahaha',
    14.2: '(Roof!)',
    14.7: 'Fuck rap',
    15.2: 'Bustin\' like an addict with a semi-automatic',
    16.6: 'Who done had it, and he ready for anybody to buck back',
    18.2: 'Hold up, catch a vibe, ain\'t no way in hell we leavin\' nobody alive',
    20.7: 'Leave a suicide note, fuck that',
    21.5: 'Bobby feelin\' villainous, he killin\' this',
    23.5: 'I\'m comin\' for your man and his lady and even the baby',
    25.2: 'I\'m feelin\' like I\'m, chika-chika-chika, Slim Shady with rabies',
    27.9: 'I\'m foamin\' at the mouth, ain\'t nobody takin\' me out',
    29.2: 'Every single rapper in the industry, yeah, they know what I\'m about',
    30.8: 'And I dare you to test me',
    32.2: '\'Cause not a single one of you motherfuckers impress me',
    33.9: 'And maybe that\'s a little bit of an exaggeration',
    35.2: 'But I\'m full of innovation',
    36.4: 'And I\'m tired of all this high school "He\'s cool, he\'s not" rap shit',
    39.8: 'Can a single one of you motherfuckers even rap? Shit',
    42.1: 'No, this ain\'t a diss to the game, this a gass to the flame',
    43.9: 'Nowadays, everybody sound the same, shit\'s lame',
    45.7: 'Like a moth to the flame, I\'ma reel \'em in and kill \'em',
    48.1: 'Knowing you feelin\' lyricism when I\'m spillin\' it, I\'m feelin\' myself',
    49.6: 'Yeah, yeah, Bobby Boy, he be feelin\' himself',
    51.4: 'Mass murder like this can\'t be good for my health',
    53.1: 'When I rap like this, do I sound like shit?',
    54.8: 'Well, it don\'t really matter, \'cause I\'m killin\' this shit',
    56.4: 'Yeah, I\'m killin\' this shit',
    57.4: 'Oh yeah, oh yeah, I\'m killin\' this shit',
    59.3: 'Bobby, how many times you been killin\' this shit?',
    61.1: 'Find another rhyme, goddamn, nigga, shit',
    62.7: 'Fuck rap',
    63.2: 'Bustin\' like an addict with a semi-automatic',
    64.6: 'Who done had it, and he ready for anybody to buck back',
    66.2: 'Hold up, catch a vibe, ain\'t no way in hell we leavin\' nobody alive',
    68.7: 'Leave a suicide note, fuck that',
    69.9: 'Bobby feelin\' villainous, he killin\' this',
  },
  'Sunburn': {
    18.9: 'You\'re the one \'til my tan fades away',
    22.9: 'Get on a train and we\'ll be strangers again',
    28.1: 'You\'re the one \'til my tan fades away',
    32.1: 'Get on a train and we\'ll be strangers again',
    36.1: 'We\'ll be strangers again',
    38.3: 'We\'ll be strangers again',
    40.6: 'We\'ll be strangers again',
    42.8: 'We\'ll be strangers again',
    45.1: 'We\'ll be strangers again...',
    91.5: 'You\'re the one \'til my tan fades away',
    95.4: 'Get on a train and we\'ll be strangers again',
    100.5: 'You\'re the one \'til my tan fades away',
    104.5: 'Get on a train and we\'ll be strangers again',
    108.5: 'We\'ll be strangers again',
    117.5: 'We\'ll be strangers again',
    126.5: 'We\'ll be strangers again',
    135.6: 'We\'ll be strangers again',
    182.1: 'You\'re the one \'til my tan fades away',
    186.1: 'Get on a train and we\'ll be strangers again',
    191.1: 'You\'re the one \'til my tan fades away',
    195.1: 'Get on a train and we\'ll be strangers again',
  }
}


class Lyrics {
  constructor (name) {
    return this.getLyrics(name);
  }

  getLyrics (name) {
    return SONGS[name];
  }
}

module.exports = Lyrics;